### ISSUE TITLE
few questions about chemview

### ISSUE THREAD

**Issue by hainm** [gabrielelanaro/chemview#18]
Hi Gabriele,

I initially fork mdtraj.html module to separated package, name [mdview] (https://github.com/mdview/mdview).
However @rmcgibbo pointed out that I should look at your chemview package.

I've tried `chemview` with [pytraj] (https://github.com/Amber-MD/pytraj) and this seems quite easy to plug to chemview

![screenshot](https://cloud.githubusercontent.com/assets/4451957/10740761/57bb6bb0-7bfa-11e5-9ec4-65b6052261ed.png)

So I just have few question?
- What's about potential of renaming `chemview` to something more general, like for biology structure (protein, membrane, ...)

- re-lisence chemview to something less restricted, like BSD or MIT?

- considering implement (or including) pv's javascript code? https://biasmv.github.io/pv/demo.html 

Let me know what you think. thanks.

**Comment by gabrielelanaro** [comment]
Hi thanks for your interest in chemview!
  - regarding the name, that would be a good move in getting more users. On the other hand chemview doesn't currently have much stuff for proteins and membranes: reason is that I deal with different kind of systems so I don't know what their needs are. What kind of keywords did you have in mind?

  - I did a brief checking of the code I used and it is mostly MIT. In this week I'll double check and update license to MIT.

- pv is a very impressive project because it doesn't uses three.js but everything is implemented from scratch. Other aspect is (I believe) that it's targeted to one-off viewing rather than trajectory animation (a very different problem). We can grab some of the code/algorithms, but they require some re-work. Did you have any specific feature you'd like to see?

**Comment by hainm** [comment]
>  What kind of keywords did you have in mind?

md3d? (since you mentions this `Other aspect is (I believe) that it's targeted to one-off viewing rather than trajectory animation (a very different problem).`)

> Did you have any specific feature you'd like to see?

Good molecule representation. Currently the color, representation in chemview is still very mature. (Don't ask me how to make it nicer because I am not really good at graphics). You can have look at https://github.com/3dmol/3Dmol.js. It's has very good graphics, BS license and seem doable to plug other trajectory reading program to 3Dmol (https://github.com/avirshup/py3dmol).

In my opinion developing those kind of things from scratch will be wonderful experience but it's really hard to make a good one, unless you have more time + funding (like pymol, vmd). So I think it's better to built on top of others. Currently I am interested to see a package that integrate well with jupyter notebook (like chemview), so I can plug my program [pytraj] (https://github.com/Amber-MD/pytraj). What's I have in mind is to load to chemview, getting pretty graphics, doing some animation, save png files or movie...

**Comment by gabrielelanaro** [comment]
Thanks for pointing to the 3DMol project that looks good they have support for trajectories, I'll take a closer look on what we can use.

Chemview was inspired from was, because it is based on THREE.js which is basically a framework for WebGL. My idea is to have a very lightweight javascript frontend and most of the work is done in Python. (for example, no need to parse PDBs in the frontend).

In term of graphics quality.. next step would be to add some "ribbon representation" for proteins plus some fancier "cartoonish" shading.

However what I learnt from my other project "chemlab" is that OpenGL is not really good for producing "publication ready" pictures. 

For that aspect I implemented a renderer based of povray that I actually use for putting images into papers, I need to update the documentation but I have very little time lately

An example using RepresentationViewer, but since TrajectoryViewer is a subclass of RepresentationViewer you can use that as well (all you need is a get_scene method):

https://github.com/gabrielelanaro/chemview/blob/master/notebooks/TestPovray.ipynb

**Comment by hainm** [comment]
thanks for the pointer to the render. I've checked it few day ago. You need to update the doc in your code that rendering need both `vapory` and `povray`
